### ISSUE TITLE
It would be nice if chat was remember between logging out and in

### ISSUE THREAD

**Issue by magnus-ISU** [tierrif/chat-utils#11]
I don't know of any fabric mod that does this, and I think it would make sense for this to do it.

**Comment by Scarlaid** [comment]
[CompactChat](https://modrinth.com/mod/compactchat)

**Comment by tierrif** [comment]
This is definitely not a bad idea, as it completely fits into what chat-utils exists for, and should keep the mod light which is also one of my objectives. I will implement this when I can. Thanks.
