### ISSUE TITLE
1.5.3

### ISSUE THREAD

**Issue by Tyler14a** [tierrif/chat-utils#21]
Multi line anti spam does not work on the 1.18 version. Experimental version does not work at all either not even for copying most messages.

**Comment by Tyler14a** [comment]
![Screenshot from 2022-12-18 20-31-00](https://user-images.githubusercontent.com/42193180/208331129-896c36fa-5462-4b5e-b67c-20c624b000a5.png)

Image is a sample of what happens in mod version 1.5.3. (In version 1.6.0 no chat collapse would occur at all, yes the setting was enabled)

**Comment by tierrif** [comment]
The experimental version is not meant to be used, nor is any old version supported. Anti spam only started to work properly on 1.19. Backport versions will not exist as of right now. Anyone is welcome to fork, but I will not be accepting PRs for this.
