### ISSUE TITLE
Looks like anti-spam toggle setting is ignored 

### ISSUE THREAD

**Issue by Fluboxer** [tierrif/chat-utils#31]
Same tech stuff as in my other reports 

From #28 I decided to disable anti-spam to temporarily solve this issue - and looks like this toggle is also broken
It seems to respect "anti-spam range" tho, so setting it to 1 makes it trigger very rarely 

![изображение](https://github.com/tierrif/chat-utils/assets/36457056/06f4f29b-f071-4410-8277-c656e87a6ae6)
![изображение](https://github.com/tierrif/chat-utils/assets/36457056/8841c646-061a-4f93-9086-be423413290c)

**Comment by tierrif** [comment]
The range is the amount of messages that will be checked for spam, 1 would mean no messages would be checked at all, only the previous one. 16, for example, checks for 16 lines before the message was received, and collapses anything equal.

This is not a bug.
