### ISSUE TITLE
Is it worth waiting for this wonderful mod on Forge?

### ISSUE THREAD

**Issue by DonorKrovi** [tierrif/chat-utils#37]
I really liked your mod and would love to play with it on Forge as there are more of my favorite mods!

**Comment by tierrif** [comment]
Unfortunately I don't have the time or the motivation to make a forge port as of right now. Chat Utils used to originally be a forge mod on its very first days but I immediately switched to fabric as it's a much more appropriate API. Forge is too problematic.

However, I obviously am not stopping anyone from making a port themselves. This project's license very clearly allows that. Thank you for your suggestion, nevertheless.
