### ISSUE TITLE
1.10.1 - 1.20.1 | Crash when copying player messages

### ISSUE THREAD

**Issue by Sotumney** [tierrif/chat-utils#42]
**Issue:**
Copying a normal message with colors works, however, copying a player's message instantly crashes the game. The crash log relates to the adventure (API) library.

**Steps for reproduction**:

1. Have ChatUtils 1.10.1 installed
2. Join server
3. Copy any player message
4. Crash

**Note:** does not occur when in 1.10.0 (possibly related to color fix)

Crash log:
[crash-2023-11-06_20.22.28-client.txt](https://github.com/tierrif/chat-utils/files/13272389/crash-2023-11-06_20.22.28-client.txt)

Full modlist:
[Modlist IBR 1.6-RC2.txt](https://github.com/tierrif/chat-utils/files/13272411/Modlist.IBR.1.6-RC2.txt)

Full game log of crash reproduction:
[2023-11-06-7.log](https://github.com/tierrif/chat-utils/files/13272398/2023-11-06-7.log)

**Comment by tierrif** [comment]
#40 this should fix this issue, as 1.10.2+1.20.2 is known to fix this (you can try that version and see if it still happens under the same settings and it shouldn't)

**Comment by Sotumney** [comment]
While I understand that that fixes it, 1.10.2 is not backwards compatible with 1.20.1. Due to the nature of our modpack, certain specific mods like OpenBoatUtils require that I stick to that version for the public to get the best compatibility with current boat physics and tracks.
However, 1.10.2 does list on Modrinth that it's compatible with any 1.20.x, but seemingly crashes the client on start-up.

**Comment by tierrif** [comment]
As I said, #40 will fix this. I don't usually do retrocompatibility but I will this one time.
