### ISSUE TITLE
the anti-spam doesn't seem to apply to others

### ISSUE THREAD

**Issue by Scarlaid** [tierrif/chat-utils#5]
Comparing is dumb, but I'm pretty sure blocking other types of messages is possible, as how Lunar Client handle them
Chat Utils isn't though
![image](https://user-images.githubusercontent.com/90851437/170810867-fc5d64d9-a1fa-407b-9b3d-d111eb7d478f.png)

**Comment by tierrif** [comment]
I'm extremely busy with college, so this will take time to fix if I do it on my own. I'm aware some messages don't collapse, can't even find a way to reproduce that yet, so PRs (or at least methods to reproduce these) are welcome.

**Comment by Scarlaid** [comment]
This messages are from a server plugin known as WorldGuard, purpose is like world protection but more independance and more stuff involves
To reproduce, it's pretty simple:
- Make a server with WorldGuard and WorldEdit
- Find some land you want to protect
- Use the axe from `//wand` and choose the corners (at least 3 blocks high)
- Stand in that area then type `/rg define (name it whatever you want)` and it should show a magenta message
- De-op yourself and try breaking stuff inside that protected area
The message will pop up like in the picture, spam it and you will get the resuilt like me

**Comment by TierriFerreira** [comment]
Nono, I know that's WorldGuard, I'm saying ways to reproduce any message that will for some reason not collapse -- I have seen it happen with messages that are longer than a full line (and end up line-breaking), so the only thing I can really think of is that the WorldGuard message is full-length and for some reason reproduces the same bug

**Comment by tierrif** [comment]
Nono, I'm aware that's WorldGuard, what I'm talking about is having steps to reproduce any message that fails to collapse normally.
I am aware this happens with messages that are so long they line-break (as the client considers these separate messages, and multi-message spam filter isn't supported yet), and for whatever reason WorldGuard messages, even not being multi-line, never collapse - which I still don't understand why.
The only thing I can think of right now is in case WorldGuard adds any metadata to each chat message, such as chat hover and/or click events, making them differ from each other, but other than that I really can't think of anything.
I'll investigate this when I have time, or if you manage to find more info, please don't hesitate posting it here. Thanks.

**Comment by tierrif** [comment]
![image](https://user-images.githubusercontent.com/44071180/170895474-bd21ce47-bf92-4d25-af9a-a0b3c9f55ad3.png)
So, I might have been able to find a fix for this, with a new multiline anti-spam feature. However, I don't know if it's just me, but it feels a little buggy on some sorts of chat messages. Let me know if it works fine for you.
https://github.com/tierrif/chat-utils/releases/tag/1.6.0-EXPERIMENTAL

**Comment by Scarlaid** [comment]
Looks like it's working
![image](https://user-images.githubusercontent.com/90851437/171013608-d8a085de-4aca-4f55-b33b-65beffb97b57.png)
